version: '3.8'

services:
  service1:
    build:
      context: ./service_1
    container_name: service1
    expose:
      - "8001"
    networks:
      - backend

  service2:
    build:
      context: ./service_2
    container_name: service2
    expose:
      - "8002"
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
    networks:
      - backend

networks:
  backend:

